Only install if needed

diff --git a/scripts/install.sh.tmpl b/scripts/install.sh.tmpl
--- a/scripts/install.sh.tmpl
+++ b/scripts/install.sh.tmpl
@@ -150,19 +150,27 @@ function install {
 	if [ ! -z "$ASPROG" ]; then
 		DEST="$OUT_DIR/$ASPROG"
 	fi
-	#move without sudo
-	OUT=$(mv $TMP_BIN $DEST 2>&1)
-	STATUS=$?
-	# failed and string contains "Permission denied"
-	if [ $STATUS -ne 0 ]; then
-		if [[ $OUT =~ "Permission denied" ]]; then
-			echo "mv with sudo..."
-			sudo mv $TMP_BIN $DEST || fail "sudo mv failed" 
-		else
-			fail "mv failed ($OUT)"
+
+	# check whether we need to copy
+	if command -v "conker" > /dev/null && [ "`conker --version`" == "`$TMP_BIN --version`" ]; then
+	  echo "conker is already up to date 👍"
+	else
+	  echo "a conker update needs to be installed..."
+		#move without sudo
+		OUT=$(mv $TMP_BIN $DEST 2>&1)
+		STATUS=$?
+		# failed and string contains "Permission denied"
+		if [ $STATUS -ne 0 ]; then
+			if [[ $OUT =~ "Permission denied" ]]; then
+				echo "mv with sudo..."
+				sudo mv $TMP_BIN $DEST || fail "sudo mv failed"
+			else
+				fail "mv failed ($OUT)"
+			fi
 		fi
+		echo "{{ if .MoveToPath }}Installed at{{ else }}Downloaded to{{ end }} $DEST"
 	fi
-	echo "{{ if .MoveToPath }}Installed at{{ else }}Downloaded to{{ end }} $DEST"
+
 	#done
 	cleanup
 }
